# Form implementation generated from reading ui file '/Users/tuakpina/Projects/PythonProjects/PersonalProjects/ChiperNora/SettingsWindow/settings_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(400, 450)
        self.mainLayout = QtWidgets.QVBoxLayout(SettingsDialog)
        self.mainLayout.setContentsMargins(20, 20, 20, 20)
        self.mainLayout.setSpacing(15)
        self.mainLayout.setObjectName("mainLayout")
        self.engineLayout = QtWidgets.QVBoxLayout()
        self.engineLayout.setObjectName("engineLayout")
        self.lbl_engine = QtWidgets.QLabel(parent=SettingsDialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.lbl_engine.setFont(font)
        self.lbl_engine.setObjectName("lbl_engine")
        self.engineLayout.addWidget(self.lbl_engine)
        self.cmb_engine = QtWidgets.QComboBox(parent=SettingsDialog)
        self.cmb_engine.setObjectName("cmb_engine")
        self.cmb_engine.addItem("")
        self.cmb_engine.addItem("")
        self.cmb_engine.addItem("")
        self.engineLayout.addWidget(self.cmb_engine)
        self.mainLayout.addLayout(self.engineLayout)
        self.apiLayout = QtWidgets.QVBoxLayout()
        self.apiLayout.setObjectName("apiLayout")
        self.lbl_api_desc = QtWidgets.QLabel(parent=SettingsDialog)
        self.lbl_api_desc.setObjectName("lbl_api_desc")
        self.apiLayout.addWidget(self.lbl_api_desc)
        self.txt_api_key = QtWidgets.QLineEdit(parent=SettingsDialog)
        self.txt_api_key.setObjectName("txt_api_key")
        self.apiLayout.addWidget(self.txt_api_key)
        self.mainLayout.addLayout(self.apiLayout)
        self.limitLayout = QtWidgets.QHBoxLayout()
        self.limitLayout.setObjectName("limitLayout")
        self.lbl_limit = QtWidgets.QLabel(parent=SettingsDialog)
        self.lbl_limit.setObjectName("lbl_limit")
        self.limitLayout.addWidget(self.lbl_limit)
        self.spin_word_limit = QtWidgets.QSpinBox(parent=SettingsDialog)
        self.spin_word_limit.setMinimum(1)
        self.spin_word_limit.setMaximum(10)
        self.spin_word_limit.setProperty("value", 3)
        self.spin_word_limit.setObjectName("spin_word_limit")
        self.limitLayout.addWidget(self.spin_word_limit)
        self.mainLayout.addLayout(self.limitLayout)
        self.chk_auto_start = QtWidgets.QCheckBox(parent=SettingsDialog)
        self.chk_auto_start.setObjectName("chk_auto_start")
        self.mainLayout.addWidget(self.chk_auto_start)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mainLayout.addItem(spacerItem)
        self.reset_set_btn = QtWidgets.QPushButton(parent=SettingsDialog)
        self.reset_set_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.reset_set_btn.setObjectName("reset_set_btn")
        self.mainLayout.addWidget(self.reset_set_btn)
        self.btn_save = QtWidgets.QPushButton(parent=SettingsDialog)
        self.btn_save.setObjectName("btn_save")
        self.mainLayout.addWidget(self.btn_save)

        self.retranslateUi(SettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "CipherNora Settings"))
        self.lbl_engine.setText(_translate("SettingsDialog", "Translation Engine"))
        self.cmb_engine.setItemText(0, _translate("SettingsDialog", "MyMemory (Free)"))
        self.cmb_engine.setItemText(1, _translate("SettingsDialog", "DeepL"))
        self.cmb_engine.setItemText(2, _translate("SettingsDialog", "Google Cloud"))
        self.lbl_api_desc.setText(_translate("SettingsDialog", "API Key / Email Address"))
        self.txt_api_key.setPlaceholderText(_translate("SettingsDialog", "Enter your credentials..."))
        self.lbl_limit.setText(_translate("SettingsDialog", "Word Limit (max words to trigger):"))
        self.chk_auto_start.setText(_translate("SettingsDialog", "Launch CipherNora at Startup"))
        self.reset_set_btn.setText(_translate("SettingsDialog", "Reset Settings"))
        self.btn_save.setText(_translate("SettingsDialog", "Apply and Save Settings"))
