name: Uygulama Kurulum Dosyalarını Üret

# Sadece GitHub'a kod pushladığında çalışır
on: [push]

jobs:
  build:
    name: ${{ matrix.os }} üzerinde derleniyor
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Bir makine çökse bile diğerleri işini bitirene kadar çalışmaya devam etsin
      matrix:
        # Kodun çalışacağı 3 farklı işletim sistemi
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Kodları Bilgisayara İndir
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Gerekli Kütüphaneleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install Pillow
          pip install -r requirements.txt

      - name: PyInstaller ile Klasör Olarak Derle
        shell: bash
        run: pyinstaller --onedir --noconsole --name "ChiperNora" --icon="icons/app_icon.ico" --hidden-import="actions.func_main" --hidden-import="API" --add-data "SettingsWindow:SettingsWindow" --add-data "icons:icons" main.py

      # --- 1. WINDOWS SETUP (Inno Setup) ---
      - name: Windows Installer (.exe) Oluştur
        if: matrix.os == 'windows-latest'
        run: iscc windows_kurulum_ayarlari.iss

      # --- 2. MAC DMG SETUP ---
      - name: macOS DMG Oluştur
        if: matrix.os == 'macos-latest'
        run: |
          # 1. DMG'nin içinin derli toplu görünmesi için geçici bir klasör oluşturuyoruz
          mkdir -p dist/dmg
          
          # 2. PyInstaller'ın ürettiği Mac uygulamasını bu klasöre kopyalıyoruz
          cp -r "dist/ChiperNora.app" dist/dmg/
          
          # 3. Sürükle-bırak yapabilmek için Applications klasörünün kısayolunu ekliyoruz
          ln -s /Applications dist/dmg/Applications
          
          # 4. Apple'ın kendi yerel aracıyla (sertifika sormadan) DMG dosyasını paketliyoruz
          hdiutil create -volname "ChiperNora" -srcfolder dist/dmg -ov -format UDZO "dist/ChiperNora.dmg"

      # --- 3. LINUX DEB SETUP ---
      - name: Linux .deb Paketi Oluştur
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y ruby ruby-dev rubygems build-essential
          sudo gem install --no-document fpm
          fpm -s dir -t deb -n "ChiperNora" -v 1.0.0 dist/ChiperNora=/opt/ChiperNora

      # --- SONUÇLARI KAYDET ---
      - name: Oluşan Setup Dosyalarını Yükle
        uses: actions/upload-artifact@v4
        with:
          name: Kurulum-Dosyalari-${{ matrix.os }}
          path: dist/